version: '3.1'

services:
  php-apache-environment:
    container_name: php-apache-1
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    # image: php:8.2-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - 9906:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db